version: "3.8"

services:
  app:
    build: .
    container_name: book-review
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app
      - FLASK_ENV=development
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_DEBUG=1
      - DATABASE_URL=mysql://root:password@db/book_db
      - SQL_USER=root
      - SQL_PASSWORD=password
      - SQL_NAME=book_db
      - SECRET_TOKEN=magomed
    depends_on:
      - db
    volumes:
      - .:/app
    restart: always

  db:
    image: mysql:latest
    container_name: book-db
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=book_db
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    restart: always

volumes:
  db-data:
