"""review changed

Revision ID: 5c8c91e8645c
Revises: cc61d748d74d
Create Date: 2025-05-22 16:12:34.317240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c8c91e8645c'
down_revision = 'cc61d748d74d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.create_unique_constraint('uix_user_book', ['user_id', 'book_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_constraint('uix_user_book', type_='unique')

    # ### end Alembic commands ###
